export const postsMock = [
  {
    id: 1,
    message: 'Post mock 1',
    reactions: {
      clap: 0,
      heart: 0,
    },
    createdAt: '',
    createdBy: 'asdf',
    banned: [''],
  },
  {
    id: 2,
    message: 'Post mock 2',
    reactions: {
      clap: 0,
      heart: 0,
    },
    createdAt: '',
    createdBy: 'asdf',
    banned: [''],
  },
  {
    id: 3,
    message: 'Post mock 3',
    reactions: {
      clap: 0,
      heart: 0,
    },
    createdAt: '',
    createdBy: 'asdf',
    banned: [''],
  },
  {
    id: 4,
    message: 'Post mock 4',
    reactions: {
      clap: 0,
      heart: 0,
    },
    createdAt: '',
    createdBy: 'asdf',
    banned: [''],
  },
  {
    id: 5,
    message: 'Post mock 5',
    reactions: {
      clap: 0,
      heart: 0,
    },
    createdAt: '',
    createdBy: 'asdf',
    banned: [''],
  },
  {
    id: 6,
    message: 'Post mock 6',
    reactions: {
      clap: 0,
      heart: 0,
    },
    createdAt: '',
    createdBy: 'asdf',
    banned: [''],
  },
  {
    id: 7,
    message: 'Post mock 7',
    reactions: {
      clap: 0,
      heart: 0,
    },
    createdAt: '',
    createdBy: 'asdf',
    banned: [''],
  },
  {
    id: 8,
    message: 'Post mock 8',
    reactions: {
      clap: 0,
      heart: 0,
    },
    createdAt: '',
    createdBy: 'asdf',
    banned: [''],
  },
  {
    id: 9,
    message: 'Post mock 9',
    reactions: {
      clap: 0,
      heart: 0,
    },
    createdAt: '',
    createdBy: 'asdf',
    banned: [''],
  },
  {
    id: 10,
    message: 'Post mock 10',
    reactions: {
      clap: 0,
      heart: 0,
    },
    createdAt: '',
    createdBy: 'asdf',
    banned: [''],
  },
  {
    id: 11,
    message: 'Post mock 11',
    reactions: {
      clap: 0,
      heart: 0,
    },
    createdAt: '',
    createdBy: 'asdf',
    banned: [''],
  },
  {
    id: 12,
    message: 'Post mock 12',
    reactions: {
      clap: 0,
      heart: 0,
    },
    createdAt: '',
    createdBy: 'asdf',
    banned: [''],
  },
  {
    id: 13,
    message: 'Post mock 13',
    reactions: {
      clap: 0,
      heart: 0,
    },
    createdAt: '',
    createdBy: 'asdf',
    banned: [''],
  },
  {
    id: 14,
    message: 'Post mock 14',
    reactions: {
      clap: 0,
      heart: 0,
    },
    createdAt: '',
    createdBy: 'asdf',
    banned: [''],
  },
  {
    id: 15,
    message: 'Post mock 15',
    reactions: {
      clap: 0,
      heart: 0,
    },
    createdAt: '',
    createdBy: 'asdf',
    banned: [''],
  },
  {
    id: 16,
    message: 'Post mock 16',
    reactions: {
      clap: 0,
      heart: 0,
    },
    createdAt: '',
    createdBy: 'asdf',
    banned: [''],
  },
  {
    id: 17,
    message: 'Post mock 17',
    reactions: {
      clap: 0,
      heart: 0,
    },
    createdAt: '',
    createdBy: 'asdf',
    banned: [''],
  },
  {
    id: 18,
    message: 'Post mock 18',
    reactions: {
      clap: 0,
      heart: 0,
    },
    createdAt: '',
    createdBy: 'asdf',
    banned: [''],
  },
  {
    id: 19,
    message: 'Post mock 19',
    reactions: {
      clap: 0,
      heart: 0,
    },
    createdAt: '',
    createdBy: 'asdf',
    banned: [''],
  },
  {
    id: 20,
    message: 'Post mock 20',
    reactions: {
      clap: 0,
      heart: 0,
    },
    createdAt: '',
    createdBy: 'asdf',
    banned: [''],
  },
];
